// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create-event.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events(name, description, location, date_time, user_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, location, date_time, user_id
`

type CreateEventParams struct {
	Name        string
	Description string
	Location    string
	DateTime    time.Time
	UserID      sql.NullInt64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.DateTime,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.DateTime,
		&i.UserID,
	)
	return i, err
}
